module.exports = {
  docs: {
    "Getting Started": [
      'getting-started/introduction',
      'getting-started/installation',
      'getting-started/quick-start',
    ],
    "General": [
      'general/directory-structure',
      'general/project-configuration',
      'general/credentials',
    ],
    "Stacks": [
      "stacks/introduction",
      "stacks/configuring-stacks",
      "stacks/stack-template-file",
      "stacks/naming-stacks",
      "stacks/choosing-regions",
      "stacks/choosing-accounts",
      "stacks/stack-parameters",
      "stacks/parameter-resolvers",
      "stacks/dependencies-between-stacks",
      "stacks/hooks",
      "stacks/templating-with-handlebars",
      "stacks/deploying-stacks",
    ],
    "Organizations": [
      "organizations/introduction",
      "organizations/getting-started",
      "organizations/trusted-aws-services",
      "organizations/organizational-units",
      "organizations/member-accounts",
      "organizations/policies",
      "organizations/creating-member-accounts",
      "organizations/deploying-organization",
      "organizations/deploying-stacks-to-member-accounts",
      "organizations/bootstrapping-member-accounts",
    ],
    "Deployment Targets": [
      "deployment-targets/introduction",
      "deployment-targets/deployment-configuration",
      "deployment-targets/deploying-stacks-to-targets",
    ],
    "Command Line Usage": [
      "command-line-usage/overview",
      "command-line-usage/init",
      "command-line-usage/stacks-deploy",
      "command-line-usage/stacks-undeploy",
      "command-line-usage/stacks-list",
      "command-line-usage/stacks-inspect-dependency-graph",
      "command-line-usage/org-create",
      "command-line-usage/org-describe",
      "command-line-usage/org-deploy",
      "command-line-usage/org-accounts-list",
      "command-line-usage/org-accounts-create",
      "command-line-usage/org-accounts-deploy",
      "command-line-usage/org-accounts-undeploy",
      "command-line-usage/org-accounts-bootstrap",
      "command-line-usage/org-accounts-tear-down",
      "command-line-usage/org-accounts-create-alias",
      "command-line-usage/org-accounts-delete-alias",
      "command-line-usage/targets-deploy",
      "command-line-usage/targets-undeploy",
    ],
    "Config File Reference": [
      "config-reference/project",
      "config-reference/stacks",
      "config-reference/organization",
      "config-reference/deployment-targets",
    ],
    "Examples": [
      "examples/about",
      "examples/stack-output-resolvers",
      "examples/simple-custom-resolvers",
      "examples/custom-resolver-with-stack-dependencies",
      "examples/custom-resolver-with-iam-role",
      "examples/managing-organization",
    ],
    "Upgrade Guide": [
      "upgrade-guide/from-2-to-3",
      "upgrade-guide/from-1-to-2",
      "upgrade-guide/from-0-to-1",
    ]
  },
};
